version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=fair
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_USER=apiuser
      - MYSQL_PASSWORD=userpwd
    ports:
      - '5001:3306'
    volumes:
      - db:/var/lib/mysql
      - ./../db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local