definitions:
  Fair:
    properties:
      areap:
        example: 1000
        format: int64
        type: integer
      codeDistrict:
        example: 10
        format: int64
        type: integer
      codeSubprefecture:
        example: 100
        format: int64
        type: integer
      districtName:
        description: District name
        example: Centro
        type: string
      externalId:
        example: 1
        format: int64
        type: integer
      fairName:
        description: Fair name
        example: Feira 123
        type: string
      id:
        example: 1
        format: int64
        type: integer
      latitude:
        example: -23558733
        format: int64
        type: integer
      longitude:
        example: -46550164
        format: int64
        type: integer
      neighborhood:
        example: Jardim Florido
        type: string
      number:
        example: 123a
        type: string
      reference:
        example: Em frente ao poste
        type: string
      region5:
        description: Region 05
        example: Leste
        type: string
      region8:
        description: Region 08
        example: Centro 2
        type: string
      register:
        description: Fair register
        example: 123-1
        type: string
      setcens:
        example: 10
        format: int64
        type: integer
      street:
        example: Rua Aibi
        type: string
      subprefecture:
        description: Subprefecture name
        example: Centro
        type: string
    required:
      - externalId
      - setcens
      - fairName
      - register
      - codeDistrict
      - codeSubprefecture
      - subprefecture
      - areap
      - districtName
      - region5
      - region8
      - street
      - neighborhood
      - latitude
      - longitude
    type: object
  Fairs:
    items:
      $ref: '#/definitions/Fair'
    type: array
  Response:
    properties:
      error:
        example: Some error msg
        type: string
      success:
        example: Some success msg
        type: string
    type: object
info:
  contact:
    email: jspsph@gmail.com
  description: Routes for fair API
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  title: Fair API
  version: 1.0.11
paths:
  /fair:
    delete:
      description: Deletes a fair
      operationId: deleteFair
      parameters:
        - description: The fair register field
          in: query
          name: register
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/Response'
        '400':
          description: One or more fields is invalid
          schema:
            $ref: '#/definitions/Response'
    get:
      description: Obtains a fair
      operationId: getFair
      parameters:
        - description: The fair register field
          in: query
          name: register
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/Fair'
        '400':
          description: One or more fields is invalid
          schema:
            $ref: '#/definitions/Response'
    post:
      consumes:
        - application/json
      description: Creates new fair
      operationId: createFair
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Fair'
      produces:
        - application/json
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/Response'
        '400':
          description: One or more fields is invalid
          schema:
            $ref: '#/definitions/Response'
    put:
      consumes:
        - application/json
      description: Updates a fair
      operationId: updateFair
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Fair'
      produces:
        - application/json
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/Response'
        '400':
          description: One or more fields is invalid
          schema:
            $ref: '#/definitions/Response'
  /fairs:
    get:
      description: Obtains a list of fairs
      operationId: getFairs
      parameters:
        - description: The district name
          in: query
          name: districtName
          type: string
        - description: The region5 name
          in: query
          name: region5
          type: string
        - description: The fair name
          in: query
          name: fairName
          type: string
        - description: The neighborhood name
          in: query
          name: neighborhood
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/Fairs'
        '400':
          description: One or more fields is invalid
          schema:
            $ref: '#/definitions/Response'
  /health:
    get:
      description: Checks if server is up
      parameters: []
      produces:
        - text/plain
      responses:
        '200':
          description: OK
          schema:
            example: OK
            type: string
swagger: '2.0'
x-components: {}

