// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateFairHandlerFunc turns a function with the right signature into a create fair handler
type CreateFairHandlerFunc func(CreateFairParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateFairHandlerFunc) Handle(params CreateFairParams) middleware.Responder {
	return fn(params)
}

// CreateFairHandler interface for that can handle valid create fair params
type CreateFairHandler interface {
	Handle(CreateFairParams) middleware.Responder
}

// NewCreateFair creates a new http.Handler for the create fair operation
func NewCreateFair(ctx *middleware.Context, handler CreateFairHandler) *CreateFair {
	return &CreateFair{Context: ctx, Handler: handler}
}

/* CreateFair swagger:route POST /fair createFair

Creates new fair

*/
type CreateFair struct {
	Context *middleware.Context
	Handler CreateFairHandler
}

func (o *CreateFair) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateFairParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
