// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteFairHandlerFunc turns a function with the right signature into a delete fair handler
type DeleteFairHandlerFunc func(DeleteFairParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteFairHandlerFunc) Handle(params DeleteFairParams) middleware.Responder {
	return fn(params)
}

// DeleteFairHandler interface for that can handle valid delete fair params
type DeleteFairHandler interface {
	Handle(DeleteFairParams) middleware.Responder
}

// NewDeleteFair creates a new http.Handler for the delete fair operation
func NewDeleteFair(ctx *middleware.Context, handler DeleteFairHandler) *DeleteFair {
	return &DeleteFair{Context: ctx, Handler: handler}
}

/* DeleteFair swagger:route DELETE /fair deleteFair

Deletes a fair

*/
type DeleteFair struct {
	Context *middleware.Context
	Handler DeleteFairHandler
}

func (o *DeleteFair) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteFairParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
