// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetFairHandlerFunc turns a function with the right signature into a get fair handler
type GetFairHandlerFunc func(GetFairParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFairHandlerFunc) Handle(params GetFairParams) middleware.Responder {
	return fn(params)
}

// GetFairHandler interface for that can handle valid get fair params
type GetFairHandler interface {
	Handle(GetFairParams) middleware.Responder
}

// NewGetFair creates a new http.Handler for the get fair operation
func NewGetFair(ctx *middleware.Context, handler GetFairHandler) *GetFair {
	return &GetFair{Context: ctx, Handler: handler}
}

/* GetFair swagger:route GET /fair getFair

Obtains a fair

*/
type GetFair struct {
	Context *middleware.Context
	Handler GetFairHandler
}

func (o *GetFair) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetFairParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
