// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetFairsHandlerFunc turns a function with the right signature into a get fairs handler
type GetFairsHandlerFunc func(GetFairsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFairsHandlerFunc) Handle(params GetFairsParams) middleware.Responder {
	return fn(params)
}

// GetFairsHandler interface for that can handle valid get fairs params
type GetFairsHandler interface {
	Handle(GetFairsParams) middleware.Responder
}

// NewGetFairs creates a new http.Handler for the get fairs operation
func NewGetFairs(ctx *middleware.Context, handler GetFairsHandler) *GetFairs {
	return &GetFairs{Context: ctx, Handler: handler}
}

/* GetFairs swagger:route GET /fairs getFairs

Obtains a list of fairs

*/
type GetFairs struct {
	Context *middleware.Context
	Handler GetFairsHandler
}

func (o *GetFairs) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetFairsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
