// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UpdateFairHandlerFunc turns a function with the right signature into a update fair handler
type UpdateFairHandlerFunc func(UpdateFairParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateFairHandlerFunc) Handle(params UpdateFairParams) middleware.Responder {
	return fn(params)
}

// UpdateFairHandler interface for that can handle valid update fair params
type UpdateFairHandler interface {
	Handle(UpdateFairParams) middleware.Responder
}

// NewUpdateFair creates a new http.Handler for the update fair operation
func NewUpdateFair(ctx *middleware.Context, handler UpdateFairHandler) *UpdateFair {
	return &UpdateFair{Context: ctx, Handler: handler}
}

/* UpdateFair swagger:route PUT /fair updateFair

Updates a fair

*/
type UpdateFair struct {
	Context *middleware.Context
	Handler UpdateFairHandler
}

func (o *UpdateFair) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateFairParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
