// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Fair API
//
//  Routes for fair API
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 1.0.11
//  License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//  Contact: <jspsph@gmail.com>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//    - text/plain
//
// swagger:meta
package restapi
